name: Create Release

on:
  workflow_dispatch:
    inputs:
      tagVersion:
        required: true
      message:

jobs:
  create_release:
    runs-on: self-hosted

    steps:
      # Create a release
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tagVersion }}
          release_name: ${{ github.event.inputs.tagVersion }}
          body: |
            Release Notes:
            ${{ github.event.inputs.message }}
          draft: true
          prerelease: true

      - run: echo "Release URL - ${{ steps.create_release.outputs.upload_url }}"
